version: "3.9"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=YourStrong!Passw0rd
            - MYSQL_DATABASE=bootstrap
        command:
            [
                "--default-authentication-plugin=mysql_native_password",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_0900_ai_ci",
            ]
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db/mysql-init:/docker-entrypoint-initdb.d:ro
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "--password=YourStrong!Passw0rd",
                ]
            interval: 10s
            timeout: 5s
            retries: 20

    redis:
        image: redis:7
        container_name: redis
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    mongo:
        image: mongo:7
        container_name: mongo
        # NOTE: fixed a common typo here (27107 -> 27017 on the host side)
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    minio:
        image: minio/minio:latest # pin a version; avoid :latest for reproducibility
        container_name: minio
        command: server /data --console-address ":9001"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data


    api-gateway:
        image: carrypotter007/api-gateway:latest
        container_name: api-gateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Container
            - ASPNETCORE_URLS=http://+:8080
            - SERVICES__IAM_URL=http://iam:8080
            - SERVICES__MEDIA_URL=http://media:8080
            - SERVICES__STORAGE_URL=http://storage:8080
        depends_on:
            - iam
            - media
        ports:
            - "5000:8080"

    iam:
        image: carrypotter007/iam:latest
        container_name: iam
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - ASPNETCORE_ENVIRONMENT=Container
            - ASPNETCORE_URLS=http://+:8080
            # NOTE: remove surrounding single quotes so they don’t end up in the value
            - ConnectionStrings__Default=Server=mysql;Port=3306;Database=IAMDb;User ID=root;Password=YourStrong!Passw0rd;
            - Redis__Configuration=redis:6379,abortConnect=false
        ports:
            - "5001:8080"

    media:
        image: carrypotter007/media:latest
        container_name: media
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - Mongo__ConnectionString=mongodb://mongo:27017
            - Mongo__Database=MediaDb
            - Minio__Endpoint=http://minio:9000
            - Minio__AccessKey=minioadmin
            - Minio__SecretKey=minioadmin
            - Minio__Bucket=media
        depends_on:
            - mongo
            - minio
        ports:
            - "5002:8080"

    storage:
        image: carrypotter007/storage:latest
        container_name: storage
        depends_on:
            mysql:
                condition: service_healthy
            minio:
                condition: service_started
        environment:
            - ASPNETCORE_ENVIRONMENT=Container
            - ASPNETCORE_URLS=http://+:8080
            - ConnectionStrings__Default=Server=mysql;Port=3306;Database=StorageDb;User=root;Password=YourStrong!Passw0rd;
            - Minio__Endpoint=http://minio:9000
            - Minio__AccessKey=minioadmin
            - Minio__SecretKey=minioadmin
            - Minio__Bucket=storage
        ports:
            - "5003:8080"

volumes:
    mysql_data:
    redis_data:
    mongo_data:
    minio_data:
